#!/usr/bin/env python3
"""
Frame Log Analysis Tool for Basketball Shot Detection
分析篮球投篮检测的帧日志数据

This script analyzes the detailed frame log generated by shot_detector.py
to provide statistics and insights about the detection performance.
"""

import json
import argparse
import os
import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict, Counter
from datetime import datetime
import pandas as pd

class FrameLogAnalyzer:
    def __init__(self, log_file_path):
        """
        Initialize the analyzer with a frame log file
        
        Args:
            log_file_path: Path to the frame log JSON file
        """
        self.log_file_path = log_file_path
        self.data = None
        self.load_data()
        
    def load_data(self):
        """Load and parse the frame log JSON file"""
        try:
            with open(self.log_file_path, 'r', encoding='utf-8') as f:
                raw_data = json.load(f)
                # Extract frames from the structured data
                self.data = raw_data.get('frames', [])
            from debug_logger import DebugLogger
            debug_logger = DebugLogger("frame_log_analyzer")
            debug_logger.info(f"[INFO] Successfully loaded {len(self.data)} frames from {self.log_file_path}", frame_count=0)
        except FileNotFoundError:
            debug_logger.error(f"[ERROR] File {self.log_file_path} not found", frame_count=0)
            return False
        except json.JSONDecodeError as e:
            debug_logger.error(f"[ERROR] Invalid JSON format - {e}", frame_count=0)
            return False
        return True
    
    def basic_statistics(self):
        """Generate basic statistics about the frame log"""
        if not self.data:
            return
            
        from debug_logger import DebugLogger
        debug_logger = DebugLogger("frame_log_analyzer")
        debug_logger.info("\n" + "="*60, frame_count=0)
        debug_logger.info("[Statistics] BASIC STATISTICS", frame_count=0)
        debug_logger.info("="*60, frame_count=0)
        
        total_frames = len(self.data)
        debug_logger.info(f"Total frames analyzed: {total_frames}", frame_count=0)
        
        # Detection statistics
        frames_with_balls = 0
        frames_with_hoops = 0
        frames_with_current_balls = 0
        frames_with_current_hoops = 0
        
        total_ball_positions = 0
        total_hoop_positions = 0
        total_current_balls = 0
        total_current_hoops = 0
        
        for frame in self.data:
            # Check if this is the new data structure
            if 'current_frame_balls' not in frame:
                debug_logger.error("[Error] Unexpected frame data structure", frame_count=0)
                return

            # Ball positions (historical)
            ball_positions = frame.get('ball_positions', [])
            if ball_positions:
                frames_with_balls += 1
                total_ball_positions += len(ball_positions)

            # Hoop positions (historical)
            hoop_positions = frame.get('hoop_positions', [])
            if hoop_positions:
                frames_with_hoops += 1
                total_hoop_positions += len(hoop_positions)

            # Current frame detections
            current_balls = frame.get('current_frame_balls', [])
            if current_balls:
                frames_with_current_balls += 1
                total_current_balls += len(current_balls)

            current_hoops = frame.get('current_frame_hoops', [])
            if current_hoops:
                frames_with_current_hoops += 1
                total_current_hoops += len(current_hoops)
        
        debug_logger.info(f"\n[History] HISTORICAL BALL/HOOP POSITIONS:", frame_count=0)
        debug_logger.info(f"  Frames with ball positions: {frames_with_balls} ({frames_with_balls/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Frames with hoop positions: {frames_with_hoops} ({frames_with_hoops/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Total ball positions: {total_ball_positions}", frame_count=0)
        debug_logger.info(f"  Total hoop positions: {total_hoop_positions}", frame_count=0)
        debug_logger.info(f"  Avg ball positions per frame: {total_ball_positions/total_frames:.2f}", frame_count=0)
        debug_logger.info(f"  Avg hoop positions per frame: {total_hoop_positions/total_frames:.2f}", frame_count=0)
        
        debug_logger.info(f"\n[Detection] CURRENT FRAME DETECTIONS (YOLO Raw Output):", frame_count=0)
        debug_logger.info(f"  Frames with ball detections: {frames_with_current_balls} ({frames_with_current_balls/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Frames with hoop detections: {frames_with_current_hoops} ({frames_with_current_hoops/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Total current ball detections: {total_current_balls}", frame_count=0)
        debug_logger.info(f"  Total current hoop detections: {total_current_hoops}", frame_count=0)
        debug_logger.info(f"  Avg ball detections per frame: {total_current_balls/total_frames:.2f}", frame_count=0)
        debug_logger.info(f"  Avg hoop detections per frame: {total_current_hoops/total_frames:.2f}", frame_count=0)
    
    def confidence_analysis(self):
        """Analyze confidence scores of detections"""
        if not self.data:
            return
            
        from debug_logger import DebugLogger
        debug_logger = DebugLogger("frame_log_analyzer")
        debug_logger.info("\n" + "="*60, frame_count=0)
        debug_logger.info("[Confidence] CONFIDENCE ANALYSIS", frame_count=0)
        debug_logger.info("="*60, frame_count=0)
        
        ball_confidences = []
        hoop_confidences = []
        position_ball_confidences = []
        position_hoop_confidences = []
        
        for frame in self.data:
            # Current frame detections
            current_balls = frame.get('current_frame_balls', [])
            for ball in current_balls:
                ball_confidences.append(ball['confidence'])
            
            current_hoops = frame.get('current_frame_hoops', [])
            for hoop in current_hoops:
                hoop_confidences.append(hoop['confidence'])
            
            # Position data (historical)
            ball_positions = frame.get('ball_positions', [])
            for ball in ball_positions:
                position_ball_confidences.append(ball['confidence'])
                
            hoop_positions = frame.get('hoop_positions', [])
            for hoop in hoop_positions:
                position_hoop_confidences.append(hoop['confidence'])
        
        # Current frame detections analysis
        if ball_confidences:
            debug_logger.info(f"\n[Ball Detection] CURRENT FRAME BALL DETECTIONS:", frame_count=0)
            debug_logger.info(f"  Count: {len(ball_confidences)}", frame_count=0)
            debug_logger.info(f"  Confidence - Min: {min(ball_confidences):.3f}, Max: {max(ball_confidences):.3f}", frame_count=0)
            debug_logger.info(f"  Confidence - Mean: {np.mean(ball_confidences):.3f}, Std: {np.std(ball_confidences):.3f}", frame_count=0)
            debug_logger.info(f"  Above 0.5: {sum(1 for c in ball_confidences if c > 0.5)} ({sum(1 for c in ball_confidences if c > 0.5)/len(ball_confidences)*100:.1f}%)", frame_count=0)
        
        if hoop_confidences:
            debug_logger.info(f"\n[Hoop Detection] CURRENT FRAME HOOP DETECTIONS:", frame_count=0)
            debug_logger.info(f"  Count: {len(hoop_confidences)}", frame_count=0)
            debug_logger.info(f"  Confidence - Min: {min(hoop_confidences):.3f}, Max: {max(hoop_confidences):.3f}", frame_count=0)
            debug_logger.info(f"  Confidence - Mean: {np.mean(hoop_confidences):.3f}, Std: {np.std(hoop_confidences):.3f}", frame_count=0)
            debug_logger.info(f"  Above 0.6: {sum(1 for c in hoop_confidences if c > 0.6)} ({sum(1 for c in hoop_confidences if c > 0.6)/len(hoop_confidences)*100:.1f}%)", frame_count=0)
        
        # Position data analysis
        if position_ball_confidences:
            debug_logger.info(f"\n[Ball Position] HISTORICAL BALL POSITIONS:", frame_count=0)
            debug_logger.info(f"  Count: {len(position_ball_confidences)}", frame_count=0)
            debug_logger.info(f"  Confidence - Min: {min(position_ball_confidences):.3f}, Max: {max(position_ball_confidences):.3f}", frame_count=0)
            debug_logger.info(f"  Confidence - Mean: {np.mean(position_ball_confidences):.3f}, Std: {np.std(position_ball_confidences):.3f}", frame_count=0)
        
        if position_hoop_confidences:
            debug_logger.info(f"\n[Hoop Position] HISTORICAL HOOP POSITIONS:", frame_count=0)
            debug_logger.info(f"  Count: {len(position_hoop_confidences)}", frame_count=0)
            debug_logger.info(f"  Confidence - Min: {min(position_hoop_confidences):.3f}, Max: {max(position_hoop_confidences):.3f}", frame_count=0)
            debug_logger.info(f"  Confidence - Mean: {np.mean(position_hoop_confidences):.3f}, Std: {np.std(position_hoop_confidences):.3f}", frame_count=0)
    
    def detection_timeline(self):
        """Analyze detection patterns over time"""
        if not self.data:
            return
            
        from debug_logger import DebugLogger
        debug_logger = DebugLogger("frame_log_analyzer")
        debug_logger.info("\n" + "="*60, frame_count=0)
        debug_logger.info("[Timeline] DETECTION TIMELINE ANALYSIS", frame_count=0)
        debug_logger.info("="*60, frame_count=0)
        
        timeline_data = []
        for frame in self.data:
            frame_info = {
                'frame': frame['frame_idx'],
                'current_balls': len(frame.get('current_frame_balls', [])),
                'current_hoops': len(frame.get('current_frame_hoops', [])),
                'ball_positions': len(frame.get('ball_positions', [])),
                'hoop_positions': len(frame.get('hoop_positions', []))
            }
            timeline_data.append(frame_info)
        
        # Find periods of high activity
        high_activity_frames = [f for f in timeline_data if f['current_balls'] > 0 or f['current_hoops'] > 0]
        
        if high_activity_frames:
            debug_logger.info(f"Frames with detections: {len(high_activity_frames)}", frame_count=0)
            debug_logger.info(f"Detection rate: {len(high_activity_frames)/len(timeline_data)*100:.1f}%", frame_count=0)

    def detection_comparison(self):
        """Compare position data vs current frame detections"""
        if not self.data:
            return

        from debug_logger import DebugLogger
        debug_logger = DebugLogger("frame_log_analyzer")
        debug_logger.info("\n" + "="*60, frame_count=0)
        debug_logger.info("[Comparison] HISTORICAL POSITIONS vs CURRENT DETECTIONS COMPARISON", frame_count=0)
        debug_logger.info("="*60, frame_count=0)

        frames_with_both_ball = 0
        frames_with_both_hoop = 0
        frames_positions_only_ball = 0
        frames_positions_only_hoop = 0
        frames_current_only_ball = 0
        frames_current_only_hoop = 0

        for frame in self.data:
            has_ball_positions = len(frame.get('ball_positions', [])) > 0
            has_hoop_positions = len(frame.get('hoop_positions', [])) > 0
            has_current_balls = len(frame.get('current_frame_balls', [])) > 0
            has_current_hoops = len(frame.get('current_frame_hoops', [])) > 0

            # Ball comparison
            if has_ball_positions and has_current_balls:
                frames_with_both_ball += 1
            elif has_ball_positions and not has_current_balls:
                frames_positions_only_ball += 1
            elif not has_ball_positions and has_current_balls:
                frames_current_only_ball += 1

            # Hoop comparison
            if has_hoop_positions and has_current_hoops:
                frames_with_both_hoop += 1
            elif has_hoop_positions and not has_current_hoops:
                frames_positions_only_hoop += 1
            elif not has_hoop_positions and has_current_hoops:
                frames_current_only_hoop += 1

        total_frames = len(self.data)

        debug_logger.info(f"[Ball Comparison] BALL DATA COMPARISON:", frame_count=0)
        debug_logger.info(f"  Both historical & current: {frames_with_both_ball} ({frames_with_both_ball/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Historical positions only: {frames_positions_only_ball} ({frames_positions_only_ball/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Current detection only: {frames_current_only_ball} ({frames_current_only_ball/total_frames*100:.1f}%)", frame_count=0)

        debug_logger.info(f"\n[Hoop Comparison] HOOP DATA COMPARISON:", frame_count=0)
        debug_logger.info(f"  Both historical & current: {frames_with_both_hoop} ({frames_with_both_hoop/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Historical positions only: {frames_positions_only_hoop} ({frames_positions_only_hoop/total_frames*100:.1f}%)", frame_count=0)
        debug_logger.info(f"  Current detection only: {frames_current_only_hoop} ({frames_current_only_hoop/total_frames*100:.1f}%)", frame_count=0)

    def bbox_size_analysis(self):
        """Analyze bounding box sizes of current detections"""
        if not self.data:
            return

        from debug_logger import DebugLogger
        debug_logger = DebugLogger("frame_log_analyzer")
        debug_logger.info("\n" + "="*60, frame_count=0)
        debug_logger.info("[Size] BOUNDING BOX SIZE ANALYSIS", frame_count=0)
        debug_logger.info("="*60, frame_count=0)

        ball_sizes = []
        hoop_sizes = []
        ball_areas = []
        hoop_areas = []

        for frame in self.data:
            current_balls = frame.get('current_frame_balls', [])
            for ball in current_balls:
                size = ball['size']
                ball_sizes.append((size['width'], size['height']))
                ball_areas.append(size['width'] * size['height'])

            current_hoops = frame.get('current_frame_hoops', [])
            for hoop in current_hoops:
                size = hoop['size']
                hoop_sizes.append((size['width'], size['height']))
                hoop_areas.append(size['width'] * size['height'])

        if ball_sizes:
            widths = [s[0] for s in ball_sizes]
            heights = [s[1] for s in ball_sizes]
            debug_logger.info(f"\n[Ball Size] BALL BOUNDING BOXES:", frame_count=0)
            debug_logger.info(f"  Count: {len(ball_sizes)}", frame_count=0)
            debug_logger.info(f"  Width - Min: {min(widths)}, Max: {max(widths)}, Mean: {np.mean(widths):.1f}", frame_count=0)
            debug_logger.info(f"  Height - Min: {min(heights)}, Max: {max(heights)}, Mean: {np.mean(heights):.1f}", frame_count=0)
            debug_logger.info(f"  Area - Min: {min(ball_areas)}, Max: {max(ball_areas)}, Mean: {np.mean(ball_areas):.1f}", frame_count=0)

            # Aspect ratio analysis
            aspect_ratios = [w/h for w, h in ball_sizes]
            debug_logger.info(f"  Aspect Ratio - Min: {min(aspect_ratios):.2f}, Max: {max(aspect_ratios):.2f}, Mean: {np.mean(aspect_ratios):.2f}", frame_count=0)

        if hoop_sizes:
            widths = [s[0] for s in hoop_sizes]
            heights = [s[1] for s in hoop_sizes]
            debug_logger.info(f"\n[Hoop Size] HOOP BOUNDING BOXES:", frame_count=0)
            debug_logger.info(f"  Count: {len(hoop_sizes)}", frame_count=0)
            debug_logger.info(f"  Width - Min: {min(widths)}, Max: {max(widths)}, Mean: {np.mean(widths):.1f}", frame_count=0)
            debug_logger.info(f"  Height - Min: {min(heights)}, Max: {max(heights)}, Mean: {np.mean(heights):.1f}", frame_count=0)
            debug_logger.info(f"  Area - Min: {min(hoop_areas)}, Max: {max(hoop_areas)}, Mean: {np.mean(hoop_areas):.1f}", frame_count=0)

            # Aspect ratio analysis
            aspect_ratios = [w/h for w, h in hoop_sizes]
            debug_logger.info(f"  Aspect Ratio - Min: {min(aspect_ratios):.2f}, Max: {max(aspect_ratios):.2f}, Mean: {np.mean(aspect_ratios):.2f}", frame_count=0)

    def generate_report(self, output_file=None):
        """Generate a comprehensive analysis report"""
        if not self.data:
            print("❌ No data loaded. Cannot generate report.")
            return
        
        from debug_logger import DebugLogger
        debug_logger = DebugLogger("frame_log_analyzer")
        
        debug_logger.info("\n" + "="*60, frame_count=0)
        debug_logger.info("[Report] BASKETBALL SHOT DETECTION - FRAME LOG ANALYSIS REPORT", frame_count=0)
        debug_logger.info("="*60, frame_count=0)
        debug_logger.info(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", frame_count=0)
        debug_logger.info(f"Log File: {self.log_file_path}", frame_count=0)
        
        # Run all analyses
        self.basic_statistics()
        self.confidence_analysis()
        self.detection_timeline()
        self.detection_comparison()
        self.bbox_size_analysis()

        debug_logger.info("\n" + "="*60, frame_count=0)
        debug_logger.info("[Complete] ANALYSIS COMPLETE", frame_count=0)
        debug_logger.info("="*60, frame_count=0)
        
        if output_file:
            # TODO: Save detailed report to file
            debug_logger.info(f"[Output] Detailed report saved to: {output_file}", frame_count=0)

def main():
    parser = argparse.ArgumentParser(description='Analyze basketball shot detection frame logs')
    parser.add_argument('log_file', help='Path to the frame log JSON file')
    parser.add_argument('--output', '-o', help='Output file for detailed report')
    parser.add_argument('--plot', '-p', action='store_true', help='Generate visualization plots')
    
    args = parser.parse_args()
    
    if not os.path.exists(args.log_file):
        from debug_logger import DebugLogger
        debug_logger = DebugLogger("frame_log_analyzer")
        debug_logger.error(f"[Error] File {args.log_file} does not exist", frame_count=0)
        return
    
    # Create analyzer and run analysis
    analyzer = FrameLogAnalyzer(args.log_file)
    analyzer.generate_report(args.output)

if __name__ == "__main__":
    main()
